// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'void App.OnLaunched(LaunchActivatedEventArgs e)', validate parameter 'e' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:Name_and_NPC_Generator.App.OnLaunched(Windows.ApplicationModel.Activation.LaunchActivatedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1725:In member void App.OnLaunched(LaunchActivatedEventArgs e), change parameter name e to args in order to match the identifier as it has been declared in void Application.OnLaunched(LaunchActivatedEventArgs args).", Justification = "<Pending>", Scope = "member", Target = "~M:Name_and_NPC_Generator.App.OnLaunched(Windows.ApplicationModel.Activation.LaunchActivatedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2201:Exception type System.Exception is not sufficiently specific.", Justification = "<Pending>", Scope = "member", Target = "~M:Name_and_NPC_Generator.App.OnNavigationFailed(System.Object,Windows.UI.Xaml.Navigation.NavigationFailedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from namespace name 'Name_and_NPC_Generator'.", Justification = "<Pending>", Scope = "namespace", Target = "~N:Name_and_NPC_Generator")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1501:'MainPage' has an object hierarchy '7' levels deep within the defining module. If possible, eliminate base classes within the hierarchy to decrease its hierarchy level below '6': 'Page, UserControl, Control, FrameworkElement, UIElement, DependencyObject, Object'", Justification = "<Pending>", Scope = "type", Target = "~T:Name_and_NPC_Generator.MainPage")]